# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10

    
  - name: Research
    identifier: research
    url: /research
    weight: 20
    
  - name: Working Papers
    url: research#working_papers
    parent: research
    weight: 22

    
  - name: Working Papers
    url: research#wip
    parent: research
    weight: 23


    

  
  - name: Teaching
    url: teaching/
    weight: 30
    
    menu: 
  - name: Resources
    identifier: resources
    url: /post/
    weight: 40
    
    menu: 
  - name: Courses and Notes
    parent: resources
    url: /post/courses
    weight: 1
    
  - name: Coding
    parent: resources
    url: /post/coding
    weight: 2
    
  - name: Misc.
    parent: resources
    url: /post/misc
    weight: 3
    
  - name: CV
    url: 'files/cv.pdf'
    weight: 50
    
  - name: Bio
    url: /bio/gallery/
    weight: 50
